Language: 'ru_ru'
Storage: mysql
Database:
  Url: 'jdbc:mysql://127.0.0.1:3306/vintraits?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false'
  TablePrefix: vintraits
  Username: root
  Password: admin
Traits:
  SecondsBetweenChange: 2592000
  AvailablePoints: 10
  BindHintPeriod: 6000
Gui:
  Simple: false
  Models:
    PrevPage: minecraft:arrow
    NextPage: minecraft:arrow
    Close: minecraft:barrier
    Review: minecraft:green_concrete
    ReviewPending: minecraft:lime_concrete
    ReviewConfirm: minecraft:lime_concrete
    Return: minecraft:barrier
    Reset: minecraft:paper
  Sounds:
    open: minecraft:entity.player.levelup
    click: minecraft:entity.player.levelup
    confirm: minecraft:entity.player.levelup